# Generated by Django 2.2.12 on 2022-04-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=3000)),
                ('category', models.CharField(max_length=3000)),
                ('image', models.CharField(max_length=3000000)),
                ('discount_percentage', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
