# Generated by Django 2.2.12 on 2022-04-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220408_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductmapping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='products.Product'),
        ),
    ]
